# Generated by Django 2.2.3 on 2019-07-25 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='common',
            name='zipCode',
            field=models.TextField(),
        ),
    ]
