# Generated by Django 2.2.3 on 2019-07-24 04:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('maps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Common',
            fields=[
                ('contentId', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('sigungu', models.IntegerField()),
                ('area', models.IntegerField()),
                ('category', models.IntegerField()),
                ('title', models.TextField()),
                ('tel', models.TextField()),
                ('overview', models.TextField()),
                ('addr1', models.TextField()),
                ('addr2', models.TextField()),
                ('homepage', models.TextField()),
                ('avgScore', models.FloatField()),
                ('zipCode', models.IntegerField()),
                ('image', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startTime', models.TextField()),
                ('endTime', models.TextField()),
                ('parking', models.TextField()),
                ('chkPet', models.TextField()),
                ('chkBaby', models.TextField()),
                ('age', models.TextField()),
                ('pay', models.TextField()),
                ('barbeque', models.TextField()),
                ('refund', models.TextField()),
                ('detailId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maps.Common')),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('inform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maps.Common')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Stamp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maps.Common')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='DetailInform',
        ),
        migrations.AddField(
            model_name='comment',
            name='inform',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maps.Common'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bookmark',
            name='inform',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maps.Common'),
        ),
        migrations.AddField(
            model_name='bookmark',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
