# Generated by Django 2.2.3 on 2019-07-25 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0002_auto_20190725_1052'),
    ]

    operations = [
        migrations.AddField(
            model_name='common',
            name='mapx',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='common',
            name='mapy',
            field=models.FloatField(default='0'),
            preserve_default=False,
        ),
    ]
